spring:
  application:
    name: 4vidia-auth
  data:
    redis:
      host: s4.java21.net
      port: 6379
      password: "*N2vya7H@muDTwdNMR!"
      database: 387
      timeout: 5000ms
jwt:
  secret: "qwertyujhgfdsazxcvbnjhgfdsqwertyuhgfdsazxcvb"

app:
  cookie:
    secure: true
    domain: ".4vidia.shop"

eureka:
  client:
    service-url:
      defaultZone: http://${ADMIN_ID}:${ADMIN_PASSWORD}@4vidia-discovery-1:8080/eureka/
server:
  port: 8080

payco:
  client-id:  ${PAYCO_CLIENT_ID}
  client-secret:  ${PAYCO_CLIENT_SECRET}
  redirect-uri: https://4vidia.shop/login/oauth2/code/payco
