spring:
  application:
    name: 4vidia-auth
  data:
    redis:
      host: s4.java21.net
      port: 6379
      password: "*N2vya7H@muDTwdNMR!"
      database: 387
      timeout: 5000ms
  jwt:
    secret: "qwertyujhgfdsazxcvbnjhgfdsqwertyuhgfdsazxcvb"

auth:
  cookie:
    secure: true

eureka:
  client:
    service-url:
      defaultZone: http://${ADMIN_ID}:${ADMIN_PASSWORD}@4vidia-discovery-1:8080/eureka/
