spring:
  application:
    name: 4vidia-auth
  jwt:
    secret: "qwertyujhgfdsazxcvbnjhgfdsqwertyuhgfdsazxcvb"

auth:
  cookie:
    secure: true

eureka:
  client:
    service-url:
      defaultZone: http://${ADMIN_ID}:${ADMIN_PASSWORD}@4vidia-discovery-1:8080/eureka/
